### ISSUE TITLE
Support type inference in conditional types ('infer')

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#101]
The following isn't supported at the moment:
```
type Elt<Container> = Container extends (infer X)[] ? X : never;
```
What's not supported is the `infer X` in the pattern `(infer X)[]`.

Documentation: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#type-inference-in-conditional-types

**Comment by resolritter** [comment]
Now that https://github.com/tree-sitter/tree-sitter-typescript/pull/114 has landed in master, I am planning to work on this one
