### ISSUE TITLE
Support rest element in tuple types such as '[any, ...any[]]'

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#104]
See [typescript playground](https://www.typescriptlang.org/play?#code/PTAEGEHtIGwGlAdwKagMYEMB2oAmyAzASy1Q1ABcBPAB1QMgCdRsXHGMrRICWLQYyDAGd+kUqGSCAtsiwUAdAChqdSqAC8oANpYArtIBGyRggXn9Rk9oC6NpWnGi2ALnVbtARjgAmOAGZ7JRBQAHVUTBx8UUY9NAo9RlQKAAsiYTYOLmEMAikqBCJ+YWRkaWFlRyxnbQwzc0MbTTYHJ1hkBRhIAHMACgAiDH6EDABKVur2zp6Bw2HQQ3HgsFCUjH41mjpq0CJeFFAk6UgAN1QpMrkKDIJGSGlKFLJ2TgB+JQxGBRpIGl7xz7fX7-D5fH5-cYhT67DJYSCISTSGjUBSgABCen4RQA5LDIPxyKpzuwmKAABwAWl6E2EUy6fUGjHmn0hKzWGwwWzkGT2SFQ0QosXiiVQRXeVRqaHqClwTS0nxpdJm-TQ8zQSxCq3WLEMkExLBwnyy3F40iIAA9kLhKLRkMJ3kTQGbLdaPJZjKZQOYFDESN1bPYQBKCYwfG5+B4ACx+UD9J4wLrzfqIJgwXD9JqgEKOkx3ZiU6lAA) for a commented example using this feature.

We want to be able to parse the following:
```typescript
type t = [any, ...any[]]
```
The spread operator `...` is allowed only in last position in the tuple type, but perhaps we could accept it in other positions if it simplifies the grammar.

**Comment by maxbrunsfeld** [comment]
Fixed in #120.
