### ISSUE TITLE
Support labeled tuple elements

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#108]
[Labeled tuple elements](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements) are a feature of typescript 4.0.
```typescript
type t = [a: string, b: number]
```

Labels are for documentation purposes only. If I understand correctly, they're not used to create or destructure tuple values.

All tuple elements must have a label, but we can be more flexible and accept some unlabeled elements if that makes the grammar simpler.

**Comment by maxbrunsfeld** [comment]
Fixed in #120.
