### ISSUE TITLE
newline before leading brace breaks function_declaration

### ISSUE THREAD

**Issue by orph** [tree-sitter/tree-sitter-typescript#130]
With tree-sitter-typescript version 0.16.1 parses this as a `(function_declaration)`: 

```
function foo() {}
```

But does not parse as a `(function_declaration)`:

```
function foo()
{}
```

Does not occur with `(function)` or `(method_definition)`

<img width="756" alt="Screen Shot 2021-01-28 at 7 09 52 PM" src="https://user-images.githubusercontent.com/28068/106218158-6ad3f400-619c-11eb-8db2-54ad9332f1cf.png">

**Comment by resolritter** [comment]
https://github.com/tree-sitter/tree-sitter-typescript/issues/95

if it's the same problem, there's #126 for this

**Comment by orph** [comment]
Fixed in 0.16.3 by #126.
