### ISSUE TITLE
Support "Template literal types"

### ISSUE THREAD

**Issue by resolritter** [tree-sitter/tree-sitter-typescript#136]
Implemented in https://github.com/microsoft/TypeScript/pull/40336

[Example syntax](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/PQKhFgCgAIWhJALgcgM7QIbQMYFdWID2AtgJYBeApgCbQBulATqqYQHbSEBm0iAFpV4BPAA6V01Sl1Jsa0GVFjQA2v1KoAugAo+iRCNQAuYMAIZsAa0INGXADaEA7gDpsJYBmABWABwAWAGYANgBOLxDgEIBGAAYQgICAdgBKRTgzS2smeydMNlRHJmc04CgoRFFBAAUmVHZoAF5oAG9FaHbSakNoAkYZAHMAbjb21Aw7DEYhbrZcYgAjJgAaEegRPkIiIxbV9o6unsQ+tiHdvdJiDH7KKox+bt6B5Q1hmD2AX1f3ssgKsWgAFKEGQAHgA0ktoFUAHyNaBg6CUAAeiEobGo6EeJ2gAH5VlVESi0RjDsd+rjVgADAAkzTB71pACJGYTUej0AScdBmdBuoznIyGc0qu9KasZpQbLzoLIbK9ypVoABBRiMDBCACidkoxDRiBBABVYU02gbWcT0IxKBhqOw7EJoFoZFwmNAtTq9QbKslnri3drdWxEF7-hK5T8-tU7nxUIbjdAzci2STCPMAFaUbCIClvdrNFQImTQCyUITcBMaAC0OO6CKTFtJAxzexb0BpdNF0AAPoDgWxwZDbvxYwblGCNNDoWd2mGmKt3soS2WeAaNNLmT8Ff8lXY7EOY3D97Gasx2NDXkA)

**Comment by danielnehrig** [comment]
Yes please add this it breaks the whole syntax highlighting in every project that is using this

**Comment by danielnehrig** [comment]
@mjambon any isight about this issue here?

**Comment by marcesengel** [comment]
Hey!

I'm sorry to ping, but I'm still having issues with this - any ideas why? Still new to NVim 🙈
<img width="618" alt="image" src="https://github.com/tree-sitter/tree-sitter-typescript/assets/6208890/c19f837a-02bc-4255-8742-5cddf904226f">
`:CheckHealth` says everything's fine with the `typescript` parser
<img width="335" alt="image" src="https://github.com/tree-sitter/tree-sitter-typescript/assets/6208890/4c9a91dc-bd27-4053-b3bd-85aa1e13fd6e">
Thanks in advance for any pointers!

**Comment by mjambon** [comment]
@marcesengel hi. Sorry for the late reply. Please file a new issue for this since it appears to be an ordinary string template, not one that's used as a type.
