### ISSUE TITLE
Support destructured function parameters in function types

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#144]
The `{x}` below is the function parameter "name", actually a destructuring pattern, given for documentation purposes:
```typescript
type t = ({x}: {x: any}) => any
```
It is supported by the [typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBMULxQBQG8AeBfAXFN2CGAdiOgJTwB8UhIAUEA) but currently not supported by tree-sitter-typescript.

**Comment by nbrahms** [comment]
I did a bit of digging, and AFAICT this is because the grammar never seems to try the `object_pattern` rule, instead beating it's head on `object_type`:

```
✗ tree-sitter parse <(echo 'let foo: ({a}: {a: string}) => number')
(program [0, 0] - [1, 0]
  (lexical_declaration [0, 0] - [0, 37]
    (variable_declarator [0, 4] - [0, 37]
      name: (identifier [0, 4] - [0, 7])
      type: (type_annotation [0, 7] - [0, 37]
        (ERROR [0, 9] - [0, 30]
          (parenthesized_type [0, 9] - [0, 27]
            (ERROR [0, 10] - [0, 14]
              (object_type [0, 10] - [0, 13]
                (property_signature [0, 11] - [0, 12]
                  name: (property_identifier [0, 11] - [0, 12]))))
            (object_type [0, 15] - [0, 26]
              (property_signature [0, 16] - [0, 25]
                name: (property_identifier [0, 16] - [0, 17])
                type: (type_annotation [0, 17] - [0, 25]
                  (predefined_type [0, 19] - [0, 25]))))))
        (predefined_type [0, 31] - [0, 37])))))
/dev/fd/11	2 ms	(ERROR [0, 9] - [0, 30])
```

**Comment by nbrahms** [comment]
I have a suspicion this might be due to automatic semicolons playing badly in this case:

![image](https://user-images.githubusercontent.com/2490631/114246703-21481800-9948-11eb-8280-5ef1009c4fa0.png)

I wonder if the lexer needs to look ahead two symbols when interpolating automatic semicolons in object types: an automatic semicolon should not be supported if there is a `:` after the closing `}`.

**Comment by maxbrunsfeld** [comment]
Nice debugging!
