### ISSUE TITLE
Parenthesized casted expression gets misinterpreted as JSX tag in TSX grammar

### ISSUE THREAD

**Issue by resolritter** [tree-sitter/tree-sitter-typescript#148]
# Code

```
const foo = (<any>1)
```

# Output

```
(program [0, 0] - [3, 0]
  (comment [0, 0] - [0, 10])
  (ERROR [2, 0] - [3, 0]
    (identifier [2, 4] - [2, 5])
    (jsx_opening_element [2, 9] - [2, 14]
      name: (identifier [2, 10] - [2, 13]))
    (jsx_text [2, 14] - [3, 0])))
foo.tsx	0 ms	(ERROR [2, 0] - [3, 0])
```

# Expectation

Should parse correctly, as the TypeScript grammar does

**Comment by resolritter** [comment]
Uh, no... Apparently TypeScript parses files differently if the syntax is JSX. That syntax is not valid if the file has a `.tsx` extension.

https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#new-tsx-file-extension-and-as-operator

https://stackoverflow.com/a/37613982

So the syntax is still valid on TypeScript, but not TSX... What the hell

**Comment by maxbrunsfeld** [comment]
Yeah, that's why we have separate grammars in this repo for TSX vs regular TypeScript. Indeed, it looks like our TypeScript grammar handles this case correctly.
