### ISSUE TITLE
JSDOC Indentation Broken on .ts (typescript)

### ISSUE THREAD

**Issue by danielnehrig** [tree-sitter/tree-sitter-typescript#154]
https://i.imgur.com/PP1emsf.png
instead of
```typescript
/**
 *
```
it does
```typescript
/**
*
```

indentation works fine for tsx

:TSInstall typescript
:TSInstall tsx

has been done and indent is enabled on ts setup lua cfg
also treesitter is the only used plugin

**Comment by mjambon** [comment]
Hey @danielnehrig, I think you might want to file this issue with some other repo that's specific to the editor plugin you're using. This repo handles only parsing, and also comments are not parsed. Maybe the tree-sitter folks have a recommendation (I'm a guest here).
