### ISSUE TITLE
is this wrong highlight in deconstructed object

### ISSUE THREAD

**Issue by PBird** [tree-sitter/tree-sitter-typescript#165]
setReady is a function and is it should be orange like in vscode 

this is screenshot from neovim 5.0 with nvim-treesitter :

![image](https://user-images.githubusercontent.com/9611415/123522874-08d6d680-d6c9-11eb-87ad-9b6e9a581569.png)

this is from vscode : 
![image](https://user-images.githubusercontent.com/9611415/123522951-69661380-d6c9-11eb-94fa-c63b7cadcfb7.png)

**Comment by resolritter** [comment]
> setReady is a function

**Syntactically**, `setReady` is an identifier. **Semantically**, the identifier is related to a function.

What you are seeing on VSCode is very likely [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) which is not done by tree-sitter, so I think this issue should be closed.
