### ISSUE TITLE
windwp/nvim-autopairs doesn't work as expected

### ISSUE THREAD

**Issue by knpwrs** [tree-sitter/tree-sitter-typescript#169]
See https://github.com/windwp/nvim-autopairs/issues/66 and https://github.com/ChristianChiarulli/LunarVim/issues/563

I have the keybindings set up, `:set indentexpr?` returns `indentexpr=nvim_treesitter#indent()`, and indent is enabled in my tree sitter settings.

When I type `function () {` I end up with the following:

```
function () {|}
```

When I press `<CR>`, I get the following:

```
function () {
|}
```

When I expect the following:

```
function () {
  |
}
```

If I'm reading those two linked issues correctly I believe this is an issue with https://github.com/tree-sitter/tree-sitter-typescript as opposed to https://github.com/windwp/nvim-autopairs.

**Comment by maxbrunsfeld** [comment]
This repository is just about parsing typescript. If you think that you're seeing an incorrect syntax tree for Typescript, then you could report it here, and include
* the source code
* the expected syntax tree
* the actual syntax tree

I think though, that you're talking about a bug/missing feature in a Vim plugin, so this would not be the repository to open the issue.
