### ISSUE TITLE
Add new `override` keyword

### ISSUE THREAD

**Issue by kmoschcau** [tree-sitter/tree-sitter-typescript#174]
Typescript 4.3 added the `override` keyword for properties, this should be added to the parser.

**Comment by mjambon** [comment]
yes, thanks! There's a PR in progress: https://github.com/tree-sitter/tree-sitter-typescript/pull/163

**Comment by kmoschcau** [comment]
Ah OK. I only searched through the issues before posting this, not the PRs. But good that it's already worked on.

**Comment by IWANABETHATGUY** [comment]
this could be closed, due to this pr https://github.com/tree-sitter/tree-sitter-typescript/pull/163 has been merged

**Comment by mjambon** [comment]
thanks for the heads up, @IWANABETHATGUY!
