### ISSUE TITLE
Rust crate seems to only highlight type annotations

### ISSUE THREAD

**Issue by LaylBongers** [tree-sitter/tree-sitter-typescript#176]
I am trying to highlight TypeScript code in an editor I'm working on in Rust, but using the Rust crate associated with this repository seems to only highlight type annotations, rather than everything part of TypeScript:

![the-machinery_3IJfwzg4lK](https://user-images.githubusercontent.com/3094382/128601637-b75d6b6e-fceb-4d71-9375-6f67c8b616ff.png)

I'm using the standard tree-sitter-highlight API for this, is there something I'm doing wrong with this?
```rust
let config = HighlightConfiguration::new(
    tree_sitter_typescript::language_typescript(),
    tree_sitter_typescript::HIGHLIGHT_QUERY,
    "",
    tree_sitter_typescript::LOCALS_QUERY,
).unwrap();
````

**Comment by mjambon** [comment]
We can't help with that here. This repo is only for the typescript grammar. If you think this is a parsing bug, please follow the instructions in the issue template. Otherwise maybe try https://github.com/tree-sitter/tree-sitter/issues
