### ISSUE TITLE
Backtick function calls cause lag

### ISSUE THREAD

**Issue by captainko** [tree-sitter/tree-sitter-typescript#179]
if I include a backtick function like below, I will be delayed after every keystroke.
The following piece of code is parsed correctly:

```typescript
class B {
  method() {
    $localize`tes`
  }
}

```

[video](https://user-images.githubusercontent.com/32269291/132936567-900ab332-8976-4795-b1ea-1dc33cb810b5.mp4)

**Comment by maxbrunsfeld** [comment]
Can you open this issue on the Neovim or `nvim-treesitter` repositories? I don't think this lag is happening inside of Tree-sitter itself.
