### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pokey** [tree-sitter/tree-sitter-typescript#199]
I see there's been lots of action in the past 9 months, but no new releases.  Would it be possible to cut a new release?  Thanks!

**Comment by amircodota** [comment]
:+1:

**Comment by tylersaunders** [comment]
Agree, would be nice to get pick up some of this great work. :+1:

**Comment by pokey** [comment]
Fwiw we've just been [installing](https://github.com/pokey/vscode-parse-tree/blob/main/package.json#L90) from the master branch

**Comment by benwis** [comment]
@maxbrunsfeld Would love a new release, we depend on this for our crate and it's broken currently in release
