### ISSUE TITLE
cannot succussfully npm install

### ISSUE THREAD

**Issue by SmartMapple** [tree-sitter/tree-sitter-typescript#224]
i'm install the tree-sitter-typescript with
`npm install`
but i get:

> tree-sitter-typescript@0.20.1 install D:\git\git_repository\tree-sitter-typescript
> node-gyp rebuild
D:\git\git_repository\tree-sitter-typescript>if not defined npm_config_node_gyp (node "D:\Nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  parser.c
  scanner.c
  parser.c
  scanner.c
D:\git\git_repository\tree-sitter-typescript\tsx\src\scanner.c : fatal error C1083: 无法打开编译器生成的文件: “D:\git\git_repositor
y\tree-sitter-typescript\build\Release\obj\tree_sitter_typescript_binding\scanner.obj”: Permission denied [D:\git\git_r
epository\tree-sitter-typescript\build\tree_sitter_typescript_binding.vcxproj]
cl : 命令行 error D8040: 创建子进程或与子进程通讯时出错 [D:\git\git_repository\tree-sitter-typescript\build\tree_sitter_typescript_bindin
g.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "D:\\Nodejs\\node.exe" "D:\\Nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\git\git_repository\tree-sitter-typescript
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-typescript@0.20.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter-typescript@0.20.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx\AppData\Roaming\npm-cache\_logs\2022-09-20T14_08_01_776Z-debug.log`

i cannot fix it, appreciate for your help

**Comment by zdaiot** [comment]
Hello, I also encountered the same problem, have you solved it?

**Comment by SmartMapple** [comment]
> @SmartMapple ，Hello, I also encountered the same problem, have you solved it?

sorry i had solved it but i forgot the solution😂. I can just recall some clue, you can try to:
1. re-install your Microsoft Visual Studio
2. check your nodejs version, and make sure your enviroument variable is configured correctly.

**Comment by zdaiot** [comment]
Thanks a lot. But Why must use the Microsoft Visual Studio

**Comment by SmartMapple** [comment]
> Thanks a lot. But Why must use the Microsoft Visual Studio

not. if you don't use Microsoft Visual Studio, you don't need install it.
