### ISSUE TITLE
Bracket type casting not supported

### ISSUE THREAD

**Issue by ryan-s-wilson** [tree-sitter/tree-sitter-typescript#232]
The following piece of code is valid but it is parsed incorrectly:

```typescript
property: PropertyType = <PropertyType>methodReturningOtherType();
```
Cloudflare is currently inaccessible in my office so I will provide the other documentation at a later time.
Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

The output of `tree-sitter parse` is the following:

```

```

**Comment by amaanq** [comment]
seems to parse fine now on master, let me know if it's still not fixed.
