### ISSUE TITLE
highlight mess

### ISSUE THREAD

**Issue by beautiful-boyyy** [tree-sitter/tree-sitter-typescript#237]
The following piece of code is valid but it is parsed incorrectly:

```typescript
import React from "react"

const DependencePage = () => {
  return (
    <>
      <div>nifs</div>
    </>
  )
}

export default DependencePage
```

The output of `tree-sitter parse` is the following:

```
Warning: You have not configured any parser directories!
Please run `tree-sitter init-config` and edit the resulting
configuration file to indicate where we should look for
language grammars.

No language found
```
![Screenshot 2023-02-17 at 15 43 38](https://user-images.githubusercontent.com/66351806/219583831-376f3cfe-9906-4bea-9101-86f2737ad79f.png)

**Comment by amaanq** [comment]
seems ok on master, let me know if not.
