### ISSUE TITLE
Type only imports and exports breaks syntax highlighting

### ISSUE THREAD

**Issue by Korywon** [tree-sitter/tree-sitter-typescript#242]
The following piece of code is valid but it is parsed incorrectly:

```typescript
import { type AppTab } from '@/types'
import {
  Button,
  Grid,
  GridItem,
  useDisclosure
} from '@chakra-ui/react'
```

Screenshot of the bug I'm seeing:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/22848944/234593462-b0df74db-9725-4b91-9492-0b928605d262.png">

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnAgmMAVAQwCM4BfOAMyghDgHIABAelQwGc6AoUSWRTuHABCAVxgwIAOwA0AuAHEowACazBilQEkY6EGrgi26ACLA2AYwA2ENiKjpO5KjXoNzACwIBrKAQC0IsBM9gTmMFxAA

The output of `tree-sitter parse` is the following:

```
❯ tree-sitter parse import-type.ts
(program [0, 0] - [7, 0]
  (import_statement [0, 0] - [0, 37]
    (import_clause [0, 7] - [0, 22]
      (named_imports [0, 7] - [0, 22]
        (import_specifier [0, 9] - [0, 20]
          name: (identifier [0, 14] - [0, 20]))))
    source: (string [0, 28] - [0, 37]
      (string_fragment [0, 29] - [0, 36])))
  (import_statement [1, 0] - [6, 25]
    (import_clause [1, 7] - [6, 1]
      (named_imports [1, 7] - [6, 1]
        (import_specifier [2, 2] - [2, 8]
          name: (identifier [2, 2] - [2, 8]))
        (import_specifier [3, 2] - [3, 6]
          name: (identifier [3, 2] - [3, 6]))
        (import_specifier [4, 2] - [4, 10]
          name: (identifier [4, 2] - [4, 10]))
        (import_specifier [5, 2] - [5, 15]
          name: (identifier [5, 2] - [5, 15]))))
    source: (string [6, 7] - [6, 25]
      (string_fragment [6, 8] - [6, 24]))))
```

I was expecting the parser to not expect `=` after the variable. When wrote `=` in front of my import, it seems to fix the highlighting. FWIW, I am using Astrovim.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**Comment by SpanishPear** [comment]
Also seeing this - perhaps related to b66d19b9b6ec3edf3d8aff0c20646acbdaa0afb3

**Comment by Korywon** [comment]
I noticed that `import type { ... } 'package'` works just fine, but doing `import { type PackageType } from 'package'` is what breaks it.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/22848944/235735689-ad408c8d-7df2-4189-a85a-741703614016.png">

<img width="261" alt="image" src="https://user-images.githubusercontent.com/22848944/235735996-52221b70-b969-4572-aa65-e9a0b7818407.png">

**Comment by sammyolo** [comment]
o dear, this is open since April 26? anything I can do to help get this fixed?

**Comment by xlboy** [comment]
T-T

**Comment by amaanq** [comment]
seems fine on master. let me know of *parse* errors if not

**Comment by yohendry** [comment]
its happening to me
