### ISSUE TITLE
[suggestion] Add a GitHub action for generating parser code

### ISSUE THREAD

**Issue by HerringtonDarkholme** [tree-sitter/tree-sitter-typescript#255]
Hi there! Thanks for maintaining TypeScript tree-sitter grammar! My [project](https://ast-grep.github.io/) relies on this parser heavily and I appreciate your work!

I have submitted a pull request recently and I found there is some friction about checking the generated parser code.

It turns out to be that tree-sitter CLI's output is platform dependent. So people who are not using `Linux x86-64` will generally fail to pass the CI check without additional help. (say using docker or asking the maintainer to force push).

One self-serving solution is using GitHub action (Thank you GH) to regenerate the parser code.

For example, this is a action YAML that people can regenerate code on their fork and commit the change to their local branch.
https://github.com/HerringtonDarkholme/tree-sitter-kotlin/blob/main/.github/workflows/regenerate-parser.yml

We can add a contributing guide so that people can set up their actions correctly. Since the above action needs to be enabled manually and to be granted read/write permission).

Hope this can reduce the friction of failing CI a lot.

**Comment by amaanq** [comment]
I'm not a fan of this honestly, it'd require a maintainer to start the workflow, rather than just keep changes together in a PR, but the friction with regenerating parser code has been a thing for a while, and requires changes potentially upstream rather than at the grammar level
