### ISSUE TITLE
feat: add `using` keyword

### ISSUE THREAD

**Issue by sigmaSd** [tree-sitter/tree-sitter-typescript#262]
https://www.totaltypescript.com/typescript-5-2-new-keyword-using

for example deno recently add support for this https://github.com/denoland/deno/commit/6dc8682b9acabea56fd69a25c28b6a8f95c2ce26 so its already being used

**Comment by amaanq** [comment]
Hey @sigmaSd, I've added support for using, hopefully Helix can update to 0.20.4 :grin:

**Comment by sigmaSd** [comment]
thanks !

**Comment by guillaumebrunerie** [comment]
This change should have been made in `tree-sitter-javascript`, `using` is a JavaScript keyword, not a TypeScript one.
