### ISSUE TITLE
tsx parser stuck in an infinite loop

### ISSUE THREAD

**Issue by sebcode** [tree-sitter/tree-sitter-typescript#265]
`tree-sitter parse` gets stuck in an infinite loop with the following code:

```typescript
const A = () => {
  return 1 ? (
    <div className=""></div>
  ) : 1 ? ( <div className="></div> ) : (
    <div>
      <input type="text" value={value} />
      <button disabled={a.b} autofocus={c.d} />
    </div>
  )
}
```

Tested with b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf

This related issue has a more verbose test-case: https://github.com/nvim-treesitter/nvim-treesitter/issues/3550

**Comment by hendrikvanantwerpen** [comment]
I suspect that this is a problem in [tree-sitter]()https://github.com/tree-sitter/tree-sitter itself. Probably better to file an issue there.

**Comment by amaanq** [comment]
It's an issue in the scanner

**Comment by jacksonneal** [comment]
> ~It's an issue in the scanner~
> 
> Nvm, I was thinking of another case similar to this one where the issue _is_ in the scanner, this is not the case and is an upstream bug

Did you end up filing an upstream bug or resolving the issue? I am running into issues on M1 mac where neovim freezes when opening a tsx file with treesitter highlighting enabled.  An infinite loop is the only reasonable explanation I can find.

**Comment by MindsightsAI** [comment]
Any workaround of this problem ?

**Comment by amaanq** [comment]
@sebcode I made a plethora of changes in the javascript parser as well as this one. Can you try it out now? If it's still stuck I'll reopen this but I'm hopeful I potentially fixed it.

**Comment by sebcode** [comment]
@amaanq The tsx parser still seems to hang :(

This is how I tested:

```
$ git clone https://github.com/tree-sitter/tree-sitter-typescript.git
$ git rev-parse HEAD
eb6b845dee9ee22987262699a152312604313662
$ cd tree-sitter-typescript/tsx/
$ tree-sitter -V
tree-sitter 0.20.9 (1d8975319c2d5de1bf710e7e21db25b0eee4bc66)
$ cat /tmp/test.tsx 
const A = () => {
  return 1 ? (
    <div className=""></div>
  ) : 1 ? ( <div className="></div> ) : (
    <div>
      <input type="text" value={value} />
      <button disabled={a.b} autofocus={c.d} />
    </div>
  )
}
$ tree-sitter parse /tmp/test.tsx
# (hangs forever)
```

If I run `tree-sitter parse` with `--debug` I can see that the parser seems to be stuck in an infinite loop.

**Comment by amaanq** [comment]
Sorry about that, I can still reproduce. I fixed another case I believe - I'll try and fix this as well

**Comment by amaanq** [comment]
Ok, I think I've actually fixed it now, I thought I had this fix in when I made my PR, but I didn't. Mind trying master?

If you *really* need a release with this fix, I can see about creating one in a few days, I'd just like some more changes in before we have another release

**Comment by amaanq** [comment]
Okay @sebcode, can you try 0.20.5? :)

**Comment by sebcode** [comment]
@amaanq This seems to work! Tested a few cases and nvim doesn't hang anymore. Thanks a lot!! :partying_face:

**Comment by wentinghome** [comment]
> Okay @sebcode, can you try 0.20.5? :)

Hi ,I 'm running into the same error when parsing on typescript. I wonder if you can apply fix to typescript also? thank you!
