### ISSUE TITLE
bug: `spell` not working within TSX/JSX

### ISSUE THREAD

**Issue by Hacksore** [tree-sitter/tree-sitter-typescript#275]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.20.9

### Describe the bug

Spell check does not seem to work inside of TSX/JSX but it will work fine in HTML so is this a bug?

Not working in JSX/TSX
<img width="1728" alt="image" src="https://github.com/tree-sitter/tree-sitter-typescript/assets/996134/050bdc05-67c9-47c1-8cfa-e73cacee51d5">

Works in HTML
<img width="886" alt="image" src="https://github.com/tree-sitter/tree-sitter-typescript/assets/996134/626d7f65-bf6b-4905-a5ba-b45f22a9140d">

### Steps To Reproduce/Bad Parse Tree

1. load up the MVP code
2. use `set spell`

### Expected Behavior/Parse Tree

The typos in the JSX/TSX should be showing underlines.

### Repro

```TypeScript
import React from "react";
import ReactDOM from "react-dom/client";
// thse is tpoes
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>thse is tpoes</React.StrictMode>
);
```

**Comment by amaanq** [comment]
not the repo for this, this is a nvim-treesitter problem.
