### ISSUE TITLE
bug: typescript syntax highlighting break when importing with the 'type' keyword

### ISSUE THREAD

**Issue by patrickswijgman** [tree-sitter/tree-sitter-typescript#276]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Describe the bug

Hello!

I've started using neovim and have installed the nvim-treesitter plugin. All treesitter health checks seem OK (and all parser features are enabled for typescript) 

![image](https://github.com/tree-sitter/tree-sitter-typescript/assets/10026055/17c86ed5-cb9f-4703-9a42-6d2b51c2b204)
![image](https://github.com/tree-sitter/tree-sitter-typescript/assets/10026055/2e63f196-d9e4-4e2e-9e69-020a26353d9c)

However when I'm importing a Typescript interface using the 'type' keyword a good portion of the code looks like a comment:

![image](https://github.com/tree-sitter/tree-sitter-typescript/assets/10026055/0d420d13-4105-406e-9b89-e65e061d6397)

I've looked through this repo for similar issues but couldn't find any, but I did find this one from another syntax highlighting plugin for typescript: https://github.com/HerringtonDarkholme/yats.vim/issues/251 where this solution within this comment fixes the issue: https://github.com/HerringtonDarkholme/yats.vim/issues/251#issuecomment-1907192414

I have no clue if this is helpful, feel free to ask anything if you need any additional information, otherwise this issue may be closed :D

### Steps To Reproduce/Bad Parse Tree

1. install https://github.com/nvim-treesitter/nvim-treesitter
2. install typescript language in tree-sitter `TSInstall typescript`
3. create a typescript file
4. import an interface using the 'type' keyword

### Expected Behavior/Parse Tree

The 'type' keyword in import statements are correctly parsed by tree-sitter

### Repro

```TypeScript
import { type ResCollection } from 'resclient';

import { initialized } from '@/lib/resgate.ts';
import { type UserAvailabilityModel } from '@/lib/types/UserAvailabilityModel.ts';
import { getUserFromStorage } from '@/lib/user.mjs';

/**
 * Get the user availabilities.
 *
 * This endpoint returns UserAvailability model that holds initial data and can be used to
 * listen for changes per user.
 */
export async function getUserAvailabilities() {
  const { clientUuid, uuid } = await getUserFromStorage();
  const resgate = await initialized();
```

**Comment by patrickswijgman** [comment]
I didn't have highlight enabled :sweat_smile: closing this issue

**Comment by lazycoder1** [comment]
Could you let us know how to enable highlight please

**Comment by crusoexia** [comment]
Facing same issue.
