### ISSUE TITLE
bug: Ampersand breaks className string on tsx

### ISSUE THREAD

**Issue by serranomorante** [tree-sitter/tree-sitter-typescript#279]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Describe the bug

![image](https://github.com/tree-sitter/tree-sitter-typescript/assets/43413954/0d32af4a-f0b6-4ed2-b417-24438cec2e33)

> Related: this also causes neovim to freeze, see: https://github.com/nvim-treesitter/nvim-treesitter/issues/6202

Only happens on `repro.tsx` file but not on `repro.ts` file.

Ampersand should be a perfectly valid char on a className=string but it is breaking syntax highlighting.

### Steps To Reproduce/Bad Parse Tree

1. Install `tsx` treesitter parser
2. Create a new file: repro.tsx
3. Add the code snippet below
4. See how the syntax highlighting breaks after the ampersand sign

> repro.tsx

```ts
function Repro() {
  return (<div className='font-bold & bg-gray-500'>Test</div>)
}
```

### Expected Behavior/Parse Tree

Syntax highlighting shouldn't break on `*.tsx` files using the `tsx` parser

### Repro

```TypeScript
This is valid react jsx/tsx code


function Repro() {
  return (<div className='font-bold & bg-gray-500'>Test</div>)
}
```

**Comment by serranomorante** [comment]
![image](https://github.com/tree-sitter/tree-sitter-typescript/assets/43413954/295e523e-3641-4d41-bc0b-3c19460de85e)

**Comment by serranomorante** [comment]
Opened an issue here: https://github.com/nvim-treesitter/nvim-treesitter/issues/6202 with a related bug

**Comment by serranomorante** [comment]
> Opened an issue here: [nvim-treesitter/nvim-treesitter#6202](https://github.com/nvim-treesitter/nvim-treesitter/issues/6202) with a related bug

From that issue:

> This is a parser issue; nothing we can do here.

**Comment by amaanq** [comment]
although it's fixed in jsx which is where the issue lies, it's not exactly fixed here yet, i probably will update parser.c within a couple hrs here as well

**Comment by serranomorante** [comment]
> although it's fixed in jsx which is where the issue lies, it's not exactly fixed here yet, i probably will update parser.c within a couple hrs here as well

Thank you so much! 🤗

**Comment by serranomorante** [comment]
> although it's fixed in jsx which is where the issue lies, it's not exactly fixed here yet, i probably will update parser.c within a couple hrs here as well

Sorry for the basic question but I just realized that the fix on `tree-sitter-javascript` also fixes the issue here on the `tree-sitter-typescript` parser automatically? Then why would you need to update this repo's `parser.c` file?

**Comment by amaanq** [comment]
ok this is actually fixed in typescript as well now, sorry for forgetting to bump js

**Comment by serranomorante** [comment]
> ok this is actually fixed in typescript as well now, sorry for forgetting to bump js

No worries! Thank you, it is working now! 👍
