### ISSUE TITLE
bug: parser stuck in infinite loop with multiple open clauses

### ISSUE THREAD

**Issue by WesleyYue** [tree-sitter/tree-sitter-typescript#281]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Describe the bug

Parsing the following code hangs forever on v0.20.5
```
try {
  console.log("foo");
} catch (err) {
  if (true) {
    console.log("bar");
  } else {
    throw new MyError(a, b
```

### Steps To Reproduce/Bad Parse Tree

No parse tree. Hangs forever.

### Expected Behavior/Parse Tree

Expect to not hang :)

### Repro

```TypeScript
try {
  console.log("foo");
} catch (err) {
  if (true) {
    console.log("bar");
  } else {
    throw new MyError(a, b
```

**Comment by wentinghome** [comment]
I run into the same problem , any luck for a fix @WesleyYue ?

> ### Did you check existing issues?
> * [x]  I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
> * [x]  I have searched the existing issues of tree-sitter-typescript
> 
> ### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)
> _No response_
> 
> ### Describe the bug
> Parsing the following code hangs forever on v0.20.5
> 
> ```
> try {
>   console.log("foo");
> } catch (err) {
>   if (true) {
>     console.log("bar");
>   } else {
>     throw new MyError(a, b
> ```
> 
> ### Steps To Reproduce/Bad Parse Tree
> No parse tree. Hangs forever.
> 
> ### Expected Behavior/Parse Tree
> Expect to not hang :)
> 
> ### Repro
> ```ts
> try {
>   console.log("foo");
> } catch (err) {
>   if (true) {
>     console.log("bar");
>   } else {
>     throw new MyError(a, b
> ```

**Comment by wentinghome** [comment]
Awesome, thank you!!

**Comment by amaanq** [comment]
np, sorry about forgetting to update this w/ the js changes
