### ISSUE TITLE
bug: highlight broken with decorators

### ISSUE THREAD

**Issue by sinelnikov-web** [tree-sitter/tree-sitter-typescript#283]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.20.8

### Describe the bug

When you specify generic type in decorator, it's break the highlight of code below

Broken
<img width="569" alt="image" src="https://github.com/tree-sitter/tree-sitter-typescript/assets/67955139/c5d54fe4-e525-41ac-9928-cecfec263769">

Normal
<img width="586" alt="image" src="https://github.com/tree-sitter/tree-sitter-typescript/assets/67955139/cc39ab2f-6158-4d01-aab6-96f91a27189f">

### Steps To Reproduce/Bad Parse Tree

1. Create a calss
2. Declare a method in this class
3. Decorate this method
4. Pass generic type in decorator

### Expected Behavior/Parse Tree

Syntax highlight will work well

### Repro

```TypeScript
function system<A>(...args: any): any {}

export default class bSrchCard   {
	@system()
	override readonly analyticsParams = {};

	@system()
	override readonly analyticsOptions = {};
}
```

**Comment by nohehf** [comment]
I can confirm, I experience the same issue:
```ts
class A {
    @decorator<T>()
    method() {
        // ...
    }
}
```

will result in the following tree:
```
(program [0, 0] - [6, 0]
  (class_declaration [0, 0] - [5, 1]
    name: (type_identifier [0, 6] - [0, 7])
    body: (class_body [0, 8] - [5, 1]
      (ERROR [1, 2] - [4, 3]
        decorator: (decorator [1, 2] - [1, 12]
          (identifier [1, 3] - [1, 12]))
        (property_identifier [1, 12] - [1, 12])
        (type_parameters [1, 12] - [1, 15]
          (type_parameter [1, 13] - [1, 14]
            name: (type_identifier [1, 13] - [1, 14])))
        (ERROR [1, 16] - [2, 10]
          (call_expression [2, 2] - [2, 10]
            function: (identifier [2, 2] - [2, 8])
            arguments: (arguments [2, 8] - [2, 10])))
        (object_pattern [2, 11] - [4, 3]
          (comment [3, 4] - [3, 10]))))))
tree-sitter-errors.ts	   0.33 ms	   173 bytes/ms	(ERROR [1, 2] - [4, 3])
```

And it works just fine without the generic type argument.
