### ISSUE TITLE
bug: `statement` node is not selected in TSPlayground

### ISSUE THREAD

**Issue by harish-prakash** [tree-sitter/tree-sitter-typescript#293]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-typescript

### Describe the bug

I'm trying to capture every kind of statement using the `statement` node but it fails.

I'm using the treesitter-playground from https://tree-sitter.github.io/tree-sitter/playground

### Steps To Reproduce/Bad Parse Tree

Here is the sample code

```ts
import {One} from 'somewhere'

const five: number = 5
```

Here is the generated tree

```
program [0, 0] - [3, 0]
  import_statement [0, 0] - [0, 29]
    import_clause [0, 7] - [0, 12]
      named_imports [0, 7] - [0, 12]
        import_specifier [0, 8] - [0, 11]
          name: identifier [0, 8] - [0, 11]
    source: string [0, 18] - [0, 29]
      string_fragment [0, 19] - [0, 28]
  lexical_declaration [2, 0] - [2, 22]
    variable_declarator [2, 6] - [2, 22]
      name: identifier [2, 6] - [2, 10]
      type: type_annotation [2, 10] - [2, 18]
        predefined_type [2, 12] - [2, 18]
      value: number [2, 21] - [2, 22]
```

I'm trying to query it with

```
(statement) @something
```

### Expected Behavior/Parse Tree

I expect it to highlight the `import_statement` and the `lexical_declaration` nodes because of the parser definition in [tree-sitter-javascript/.../node-types.json](https://github.com/tree-sitter/tree-sitter-javascript/blob/fff4560044bdc51d9f6995f1edc797b7cd72b9dc/src/node-types.json#L215-L299) (which is imported in typescript parser)

Unfortunately, it does not. However, when I use `(declaration) @something`, then it highlights the `lexical_declaration` node and when I use `(import_statement) @something` then it highlights the `import_statement` node.

**Comment by harish-prakash** [comment]
Then how come `declaration`, another supertype which is hidden in the tree, work 🤔?

> ![image](https://github.com/tree-sitter/tree-sitter-typescript/assets/32839065/5db4fa35-a800-49ba-bde5-2d23f97ca597)

**Comment by amaanq** [comment]
You're right, I was thinking about inlined rules in the context of a query, since statement is also inlined, which is weird an doesn't make sense. I'll un-inline it and update this grammar as well
