### ISSUE TITLE
feature: how can I PR an extension like tsx, but for another superset language?

### ISSUE THREAD

**Issue by NullVoxPopuli** [tree-sitter/tree-sitter-typescript#307]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

I've noticed that tree-sitter-javascript works fine for this "gjs" syntax, but "gts" falls over with an error:

![image](https://github.com/user-attachments/assets/02c02cf8-423f-4caa-bfcb-17523aa73e5e)
![image](https://github.com/user-attachments/assets/e7ed10e5-98eb-4f62-918a-68ac94f1044e)

My previous PRs to this repo were just around highlighting, but it's clear that I need to probably do some parsing work as well: https://github.com/tree-sitter/tree-sitter-typescript/pull/277

The code that supports this for javascript / the javascript flavor of glimmer, is not very big: 
https://github.com/tree-sitter/tree-sitter-javascript/pull/208/files#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR547

does this need to be duplicated in to this repo for gts (Glimmer-flavored TypeScript) support?

### Describe the solution you'd like

I can implement whatever, just need some guidance

### Describe alternatives you've considered

n/a

**Comment by amaanq** [comment]
Closing since we discussed the solution in #308
