### ISSUE TITLE
Grammar syntax scope is source.js in Atom

### ISSUE THREAD

**Issue by lierdakil** [tree-sitter/tree-sitter-typescript#58]
Reported in https://github.com/TypeStrong/atom-typescript/issues/1422 initially.

Long story short, Atom uses `.source.js` for syntax scope. Consequently, there is no way to enable autocomplete-plus provider specifically on TypeScript files.

**Comment by lierdakil** [comment]
Nevermind, figured it out. Still, spans get `syntax--js` class for some reason, which seems wrong.

**Comment by maxbrunsfeld** [comment]
I think this is fixed in the latest versions of Atom.
