### ISSUE TITLE
Improve TypeScript ?

### ISSUE THREAD

**Issue by gossi** [tree-sitter/tree-sitter-typescript#72]
Hello,

I've been trying to use tree-sitter with [One Monokai](https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai) theme.
Basically, what I do, is turn tree-sitter on, my colors are gone, and I turn it off. I don't know if there are too many tokens/scopes not being reported or if the theme doesn't support them ("one monokai" doesn't support `variable` scope - I added one locally but then almost everything turned that color).

Here is a screenshot what TS in tree-sitter looks like:

<img width="814" alt="Bildschirmfoto 2019-08-10 um 11 45 36" src="https://user-images.githubusercontent.com/283700/62820436-88ef0400-bb64-11e9-8876-dfa8629b2bc8.png">

Things that make me odd:

- The boolean and nullish constants are in a color, that one monokai is using for either invalid or numeric scopes
- property names and method names receive no highlighting, which makes navigating with visual cues quite hard

**Comment by gossi** [comment]
Here is what's been looking like WITHOUT tree-sitter (with all the inconsistencies):

<img width="815" alt="Bildschirmfoto 2019-08-10 um 11 50 33" src="https://user-images.githubusercontent.com/283700/62820482-277b6500-bb65-11e9-9b38-5f007143ccbd.png">

Yes, the highlighting is a bit insonsistent but is still better helping than tree-sitter.

**Comment by gossi** [comment]
I opened azemoh/vscode-one-monokai#34 perhapbs under a wrong understanding, maybe you can help verify.

**Comment by maxbrunsfeld** [comment]
This repository just implements parsing. The syntax highlighting configuration is [here](https://github.com/atom/language-typescript/blob/5c5dd3b0ea69e5d9ceef328599526195dc76140f/grammars/tree-sitter-typescript.cson#L38-L234), in the [language-typescript](https://github.com/atom/language-typescript) Atom package. Can you open the issue there?
