### ISSUE TITLE
JSX parse error with multi-line attribute

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-typescript#74]
@UltimateBeaver pointed out on [a Semantic issue](https://github.com/github/semantic/issues/237) that we have problems with multi-line attribute spans in TSX tags. An example:

```typescript
export default function SelectionEvents() {
  return (
    <FixtureSet
      title="Selection Restoration"
      description="selection state before commits and then restoring it afterwards.">
      <ReorderedInputsTestCase />
      <OnSelectEventTestCase />
    </FixtureSet>
  );
}
```

**Comment by maxbrunsfeld** [comment]
Wow, strings can span multiple lines in JSX. I think that means we need a separate ‘jsx_string’ rule that works differently than regular strings.

**Comment by maxbrunsfeld** [comment]
Oh wait, sorry, I misread the example. There aren't multi-line strings.

This actually parses ok with `tree_sitter_tsx` for me. Maybe it is a semantic issue after all.
