### ISSUE TITLE
`jsx_opening_element` with if-else inside of it can't be queried properly

### ISSUE THREAD

**Issue by resolritter** [tree-sitter/tree-sitter-typescript#79]
Example code

```tsx
export function Button() {
  return (
    <button
      className={style.className}
      onClick={function () {
        if (activeTheme == "light") {
          updateTheme(themes.dark)
        } else {
          updateTheme(themes.light)
        }
      }}
    >
      Change the theme
    </button>
    </>
  )
}
```

Given the following query

```
(jsx_opening_element
 "<" @operator
 ">" @operator)
```

The query weirdly yields no matches for the `<button>` element due to the if-else function inside of the `onClick` attribute. Removing the `else` statement seems to fix the problem.

EDIT: Seems to be a more general problem with any two or more expressions inside of the function's body.

i.e.

```typescript
      onClick={function () {
        const activeTheme = getActiveTheme()
        if (activeTheme == "light") {
          updateTheme(themes.dark)
        }
      }}
```

also reproduces in the same problem

**Comment by maxbrunsfeld** [comment]
I think this is a manifestation of [this bug](https://github.com/tree-sitter/tree-sitter/issues/634) in Tree-sitter's query engine. I'm working on a fix, but not sure when it will be done.

**Comment by maxbrunsfeld** [comment]
I'm going to close this out actually, and ask you to subscribe to https://github.com/tree-sitter/tree-sitter/issues/634 instead. I will verify that this specific case is fixed before closing that issue.
