### ISSUE TITLE
Why or why not a rule for a single keyword like `readonly`?

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#87]
In `define-grammar.js`, we have:

```js
        choice(
          seq(optional('static'), optional($.readonly)),
          seq(optional('abstract'), optional($.readonly)),
          seq(optional($.readonly), optional('abstract')),
        ),
```
while the `readonly` rule is just defined as follows:
```js
      readonly: $ => 'readonly',
```
The `readonly` rule is not declared as inline. Does it make a difference? Or do we use a rule for `readonly` because it appears in more places than `static` or `abstract`?

**Comment by maxbrunsfeld** [comment]
I don't know why it's a named rule. It seems like it should just be used inline, like `static` and `abstract`. I think this was somewhat arbitrary.

**Comment by mjambon** [comment]
thanks!
