### ISSUE TITLE
Tolerate newline before function or method return type

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#93]
The following is rejected:
```typescript
function f()
  : any {}
```
but it should be treated like
```typescript
function f() : any {}
```
It works with the official typescript implementation and it's being used (see [report](https://github.com/returntocorp/semgrep/issues/1713#issuecomment-702187139)).

I haven't looked into what it would take to fix this.

**Comment by maxbrunsfeld** [comment]
Automatic semicolon insertion is handled by the [external scanner](https://github.com/tree-sitter/tree-sitter-typescript/blob/master/common/scanner.h) ([docs](https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners)). There is a set of tokens (like `,`, `.`, `*`, `(`, etc) which are assumed to be line continuations, and suppress the creation of an 'automatic semicolon'.

Maybe we can just add `:` to this list? I don't think `:` can ever be the start of a statement.

**Comment by mjambon** [comment]
Great. PR is here: https://github.com/tree-sitter/tree-sitter-typescript/pull/94
