### ISSUE TITLE
Cannot parse complex type parameter on function call: 'foo<bar[]>()'

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-typescript#97]
This fails:
```typescript
foo<number[]>();
```
The parser produces an error node for `>()`.

This works:
```typescript
foo<number>();
```

**Comment by resolritter** [comment]
I have a fix for this, but changes will need to be made on tree-sitter-javascript

**Comment by resolritter** [comment]
Looks like https://github.com/tree-sitter/tree-sitter-typescript/commit/ac5dac11901ce550e11b9eda684ee6fb976cbe4a has fixed this
